# Generated by Django 4.2.6 on 2023-12-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={"ordering": ("timestamp",)},
        ),
        migrations.AddField(
            model_name="messages",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
